package:
  name: bpftool
  version: 7.2.0
  epoch: 0
  description: A collection of tool to inspect and manipulate eBPF programs

environment:
  contents:
    packages:
      - build-base
      - busybox
      - clang
      - llvm16
      - git
      - elfutils-dev
      - linux-headers
      - zstd-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libbpf/bpftool
      tag: v${{package.version}}

  - runs: |
      git submodule update --init
      cd src
      make
      DESTDIR=${{targets.destdir}} make install

  - uses: strip
