package:
  name: gops
  version: 0.3.28
  epoch: 0
  description: gops is a command to list and diagnose Go processes currently running on your system.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - go
      - git

pipeline:
  - uses: go/install
    with:
      package: github.com/google/gops
      version: v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: google/gops
    strip-prefix: v
