package:
  name: hubble
  version: 0.12.0
  epoch: 0
  description: hubble is a command to list and diagnose Go processes currently running on your system.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - go
      - git
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/hubble
      tag: v${{package.version}}

  - runs: |
      DESTDIR=${{targets.destdir}} BINDIR=/usr/bin make install

  - uses: strip

subpackages:
  - name: hubble-compat
    description: Compatibility package for hubble
    dependencies:
      runtime:
        - hubble
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/hubble ${{targets.subpkgdir}}/usr/local/bin/hubble
      - uses: strip

update:
  enabled: true
  github:
    identifier: cilium/hubble
    strip-prefix: v
